sudo: true
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - pypy3
install:
  - sudo pip install tox
  - sudo pip install hachoir-core
  - sudo pip install hachoir-parser
  - sudo pip install hachoir-regex
  - sudo pip install hachoir-subfile
script:
  - python -m py_compile script.py
