name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-lint:
    runs-on: ubuntu-latest
    name: Run linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        env:
          ghtoken: ${{ secrets.PUBLISH }}
        run: |-
          pip install tox
          pip install hachoir-core
          pip install hachoir-parser
          pip install hachoir-regex
          pip install hachoir-subfile
          python -m py_compile MediaInfoExt.py

